name: test

on:
  push:
    branches:
      - 'master'

jobs:
  readme-scribe:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4

      - run: pkg-config --help
      - run: pkg-config.exe --libs libpq
